version: '3.8'

services:
  counter:
    build:
      context: ./counter
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: counter_service

  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    container_name: notifier_service
    depends_on:
      - counter
    environment:
      # The hostname 'counter' is automatically resolved by Docker's internal DNS
      # to the IP address of the 'counter' service.
      - COUNTER_SVC_HOST=counter_service:8080
      - CHECK_INTERVAL=10s
      - EMAIL_TO=${EMAIL_TO}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}